#!/bin/bash
# at each BT connection/disconnection tell mpradio passing bluetooth address to the pipe
# env > /tmp/testenv

function log {
	sudo echo "[$(date)]: $*" > /var/log/bluetooth_dev
}
BTMAC=${NAME//\"/}

if [[ $ACTION == "remove" ]]
then
        log "Stop Bluetooth played connection " $BTMAC
	echo "bluetooth detach" > /tmp/mpradio_bt
elif [[ $ACTION == "add" ]]
then
	if [[ $BTMAC != "" ]]
	then
		log "Start Bluetooth played connection " $BTMAC
	else
		log "Start Bluetooth played connection " $BTMAC "via python script"
		BTMAC=$(a2dp_connected.py)
	fi

	if [[ $BTMAC != "" ]]; then exit; fi		

	sed -i "s/^defaults.bluealsa.device.*$/defaults.bluealsa.device \"$BTMAC\"/g" /etc/asound.conf
	echo "bluetooth attach $BTMAC" > /tmp/mpradio_bt
else
        log "Other action " $ACTION
fi

